{
  "formatVersion": "1.1",
  "component": {
    "group": "xland.gradle",
    "module": "ABSApiJarHelper",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ABSApiJarHelper-1.0.2.jar",
          "url": "ABSApiJarHelper-1.0.2.jar",
          "size": 14387,
          "sha512": "c0197fdfa1aaf66616b694794fed944df2b850ac0af50a9768f30b3f1f252988706ba3378907934d435df094ea8f997738c44c51d84958e132221e6f2e7912cd",
          "sha256": "fce47a26736cb2839d9c513dbba15e29153089f1a5fd580ba3592dafb849dcaa",
          "sha1": "05b8a4bfe3011a49dd8ebb37871905bfad06d0b7",
          "md5": "643adf7d9e94255d65bc4e11ebfd6c1f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.4"
          }
        }
      ],
      "files": [
        {
          "name": "ABSApiJarHelper-1.0.2.jar",
          "url": "ABSApiJarHelper-1.0.2.jar",
          "size": 14387,
          "sha512": "c0197fdfa1aaf66616b694794fed944df2b850ac0af50a9768f30b3f1f252988706ba3378907934d435df094ea8f997738c44c51d84958e132221e6f2e7912cd",
          "sha256": "fce47a26736cb2839d9c513dbba15e29153089f1a5fd580ba3592dafb849dcaa",
          "sha1": "05b8a4bfe3011a49dd8ebb37871905bfad06d0b7",
          "md5": "643adf7d9e94255d65bc4e11ebfd6c1f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ABSApiJarHelper-1.0.2-sources.jar",
          "url": "ABSApiJarHelper-1.0.2-sources.jar",
          "size": 7548,
          "sha512": "27b52d77e2e6276bfea4ee2868bb3b4bbfe0bceebd976112154db1ec9c8a6a9062dccb39202049e9657f0d7493d49dbe5c71494a7e1562aaa2e8cf93487a6f45",
          "sha256": "19bd8b3006a7ee69a572b07f3611ce76f5b48e0b024b367a3ba72a23a3b5d939",
          "sha1": "4082d9468da0ca009c9a30967d2ca2a4e7d6ef75",
          "md5": "a370495f64b337422e658d138e9923a0"
        }
      ]
    }
  ]
}
