{
  "formatVersion": "1.1",
  "component": {
    "group": "xland.gradle",
    "module": "forge-init-injector",
    "version": "3.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "forge-init-injector-3.0.1.jar",
          "url": "forge-init-injector-3.0.1.jar",
          "size": 41241,
          "sha512": "16b2e709f7341283affb8a189280d8c220c0c85ea9ce94fdc6933efdc8eed67c5bf917b2f02d5c68ab4692ff5bf12a00430d76613f9ebff7eaac1d4d911ab733",
          "sha256": "727e5b118af9d9cd6bf7f24fee746ee6798c4feba45fdc7e82ec40f0bd437db5",
          "sha1": "d62f074b582480139537c6bf6fb6ad1e4f7a3910",
          "md5": "35bfdaa9afbe55c8b2c0d096028bd222"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "forge-init-injector-3.0.1.jar",
          "url": "forge-init-injector-3.0.1.jar",
          "size": 41241,
          "sha512": "16b2e709f7341283affb8a189280d8c220c0c85ea9ce94fdc6933efdc8eed67c5bf917b2f02d5c68ab4692ff5bf12a00430d76613f9ebff7eaac1d4d911ab733",
          "sha256": "727e5b118af9d9cd6bf7f24fee746ee6798c4feba45fdc7e82ec40f0bd437db5",
          "sha1": "d62f074b582480139537c6bf6fb6ad1e4f7a3910",
          "md5": "35bfdaa9afbe55c8b2c0d096028bd222"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "forge-init-injector-3.0.1-sources.jar",
          "url": "forge-init-injector-3.0.1-sources.jar",
          "size": 10512,
          "sha512": "10f233ad3f17b9ad7d6ca542dc46ec975d7de22eea250db11d778b4c882a7ec4a9e45a61dbac80972efeb68a7181f10d3e5c82cd95d826c655439b7908592b90",
          "sha256": "6c79f4e602a7023d713646273478ee310b9295dcd17b2b32d733bde7184cf950",
          "sha1": "b3e679c1c3fd28d10dba27d25a1fff0d0b9310dc",
          "md5": "7f3901e9f43bc359153733f3dc2dbc39"
        }
      ]
    }
  ]
}
