{
  "formatVersion": "1.1",
  "component": {
    "group": "xland.mcmodbridge",
    "module": "fa2fomapper",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fa2fomapper-1.0.0.jar",
          "url": "fa2fomapper-1.0.0.jar",
          "size": 25304,
          "sha512": "32fbbe5068b8b670137c7f4c6dd218b300d64a983aae463ad7b618c5931b5fb59825ff08ce9e48885e509a05391b4182b67c1add4b931c1606819081a18fb0ff",
          "sha256": "1884e848bfd3d92af98525ebe84e6b6a19432996416433b52fac145d813764cf",
          "sha1": "a1f3641ba757189b37a1b210a4a0077d05ea9a96",
          "md5": "39134a63f5975d8d1192e1fba1f60e67"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "cpw.mods",
          "module": "modlauncher",
          "version": {
            "requires": "8.1.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "21.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.17.1"
          }
        }
      ],
      "files": [
        {
          "name": "fa2fomapper-1.0.0.jar",
          "url": "fa2fomapper-1.0.0.jar",
          "size": 25304,
          "sha512": "32fbbe5068b8b670137c7f4c6dd218b300d64a983aae463ad7b618c5931b5fb59825ff08ce9e48885e509a05391b4182b67c1add4b931c1606819081a18fb0ff",
          "sha256": "1884e848bfd3d92af98525ebe84e6b6a19432996416433b52fac145d813764cf",
          "sha1": "a1f3641ba757189b37a1b210a4a0077d05ea9a96",
          "md5": "39134a63f5975d8d1192e1fba1f60e67"
        }
      ]
    }
  ]
}
