{
  "formatVersion": "1.1",
  "component": {
    "group": "xland.mcmodbridge",
    "module": "fa2fomapper",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fa2fomapper-2.0.0.jar",
          "url": "fa2fomapper-2.0.0.jar",
          "size": 28390,
          "sha512": "69239601a79b75ea21d74eb11169b4931e78d26690c2420aef20e3d550ef6424f7c66a68dda446506263e49be23255dd1f01d0abd503acc82a05081f34aa4488",
          "sha256": "e0db50aedd2fb3f9d2c83b67827071ce1d4ce7f1458893d796a638c5260a3a64",
          "sha1": "5d203bac877b0c2675c637d75f78b3e91f352f4a",
          "md5": "fab6611e847464764c9f7be3b69444c0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "cpw.mods",
          "module": "modlauncher",
          "version": {
            "requires": "8.1.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "21.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.17.1"
          }
        }
      ],
      "files": [
        {
          "name": "fa2fomapper-2.0.0.jar",
          "url": "fa2fomapper-2.0.0.jar",
          "size": 28390,
          "sha512": "69239601a79b75ea21d74eb11169b4931e78d26690c2420aef20e3d550ef6424f7c66a68dda446506263e49be23255dd1f01d0abd503acc82a05081f34aa4488",
          "sha256": "e0db50aedd2fb3f9d2c83b67827071ce1d4ce7f1458893d796a638c5260a3a64",
          "sha1": "5d203bac877b0c2675c637d75f78b3e91f352f4a",
          "md5": "fab6611e847464764c9f7be3b69444c0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fa2fomapper-2.0.0-sources.jar",
          "url": "fa2fomapper-2.0.0-sources.jar",
          "size": 12637,
          "sha512": "b87454904c8b148364bc1b1f602d2bf40fa7561e1bb0d638d533f2f9256a53a5dd59c7582222940ddd6e48c51501273009cb1a46c365da8c571571059e6b2136",
          "sha256": "34bd75b36a492a3a8f851d1dedf7f40ebcb0d30bb2e58bf7c7895c45d062bf50",
          "sha1": "0ee11c216ccb3171662d49fb5395ce96c1d24319",
          "md5": "e51f1ef7a8360f793a59451ed88a53c3"
        }
      ]
    }
  ]
}
