{
  "formatVersion": "1.1",
  "component": {
    "group": "xland.gradle",
    "module": "forge-init-injector",
    "version": "3.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "forge-init-injector-3.1.0.jar",
          "url": "forge-init-injector-3.1.0.jar",
          "size": 42736,
          "sha512": "80bebef1e2e42004ecfdf8c69b645beedd2c657d0ea78f28e964679b98e265c83a1b54d3a4452220721d67b784cb168d6ede26c1e743d1a3464f44ad0879ded6",
          "sha256": "ad6783ebc0e89c8d0a475f4c8fb6202fa0c48968dccf4a69b26ddb5c038dd5e3",
          "sha1": "868113db92ebf82c71683d5faecf82b5ca2af3c5",
          "md5": "c870874181e91bb70a549a4d604a7034"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "forge-init-injector-3.1.0.jar",
          "url": "forge-init-injector-3.1.0.jar",
          "size": 42736,
          "sha512": "80bebef1e2e42004ecfdf8c69b645beedd2c657d0ea78f28e964679b98e265c83a1b54d3a4452220721d67b784cb168d6ede26c1e743d1a3464f44ad0879ded6",
          "sha256": "ad6783ebc0e89c8d0a475f4c8fb6202fa0c48968dccf4a69b26ddb5c038dd5e3",
          "sha1": "868113db92ebf82c71683d5faecf82b5ca2af3c5",
          "md5": "c870874181e91bb70a549a4d604a7034"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "forge-init-injector-3.1.0-sources.jar",
          "url": "forge-init-injector-3.1.0-sources.jar",
          "size": 10932,
          "sha512": "e98fc588a06316148c35101c62f1c1e26b34c3539f39cd00724e48fcafcbd37baac9d8230b2b6488bddff978948627a287773b12277915d32542616321e62064",
          "sha256": "e704fedec596c61e9a06e59132460bfff6680270a5ce99c44d996802f7f5861e",
          "sha1": "d943c0c4a4e7edc469a53dade1f3c6dd47ff7cc2",
          "md5": "dc9abbe6733c05efe0e156537e0178ee"
        }
      ]
    }
  ]
}
