{
  "formatVersion": "1.1",
  "component": {
    "group": "xland.gradle",
    "module": "forge-init-injector",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "forge-init-injector-1.0.1.jar",
          "url": "forge-init-injector-1.0.1.jar",
          "size": 44351,
          "sha512": "99df468de79badcb07215705dee4b859f37caab0476bf6f2a6e1a849da2bea4c1dbacba3ce90c8c64da1511a144c8b790bb06fb4b55399549ed41617cad1ad35",
          "sha256": "bc160ead2fbd2de4ee3b45e02bf190ad5d036f90b79d4969ed14aa8002758d01",
          "sha1": "051438351dc51db476448b7996c748538857ea0f",
          "md5": "1106744ae3414a1d8a66a135ff331d82"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "forge-init-injector-1.0.1.jar",
          "url": "forge-init-injector-1.0.1.jar",
          "size": 44351,
          "sha512": "99df468de79badcb07215705dee4b859f37caab0476bf6f2a6e1a849da2bea4c1dbacba3ce90c8c64da1511a144c8b790bb06fb4b55399549ed41617cad1ad35",
          "sha256": "bc160ead2fbd2de4ee3b45e02bf190ad5d036f90b79d4969ed14aa8002758d01",
          "sha1": "051438351dc51db476448b7996c748538857ea0f",
          "md5": "1106744ae3414a1d8a66a135ff331d82"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "forge-init-injector-1.0.1-sources.jar",
          "url": "forge-init-injector-1.0.1-sources.jar",
          "size": 9409,
          "sha512": "5db7188f18ca7032653c716279bb89fc6331fae62490454d4a191759ec9f45db4b0bb0e5991a9b45789318fc9207b842f2e684311648bc39a0c12ccea5679afa",
          "sha256": "117ec35ee8f84557e1ea90b3756e39bfba2e00df757a3dfa646fb29632f33c03",
          "sha1": "1a45aa9bc7fd37979543b35ad2e18dd5321c0910",
          "md5": "26ee1301093ea08d430cb5d042964709"
        }
      ]
    }
  ]
}
