{
  "formatVersion": "1.1",
  "component": {
    "group": "xland.mcmodbridge",
    "module": "fa2fomapper",
    "version": "3.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fa2fomapper-3.0.0.jar",
          "url": "fa2fomapper-3.0.0.jar",
          "size": 26500,
          "sha512": "c02136f7a38b299084bbed30e9efa112cb996200ed70e9fa37825f2010fd1437988cfcf3e9b09a396a1698493bbd44878f14e4c5164db53bf4fb66b9c8ac1e88",
          "sha256": "11ddf0b5f0dc4d3a52611c31706abde731a3a47ca6ddf8fb1e6307a0f09c5848",
          "sha1": "0fd647c8cb53bfb45ddd44476ed96d047a7223e7",
          "md5": "32f471bce306aa55e785e48315ad7059"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "cpw.mods",
          "module": "modlauncher",
          "version": {
            "requires": "8.1.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "21.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.17.1"
          }
        }
      ],
      "files": [
        {
          "name": "fa2fomapper-3.0.0.jar",
          "url": "fa2fomapper-3.0.0.jar",
          "size": 26500,
          "sha512": "c02136f7a38b299084bbed30e9efa112cb996200ed70e9fa37825f2010fd1437988cfcf3e9b09a396a1698493bbd44878f14e4c5164db53bf4fb66b9c8ac1e88",
          "sha256": "11ddf0b5f0dc4d3a52611c31706abde731a3a47ca6ddf8fb1e6307a0f09c5848",
          "sha1": "0fd647c8cb53bfb45ddd44476ed96d047a7223e7",
          "md5": "32f471bce306aa55e785e48315ad7059"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fa2fomapper-3.0.0-sources.jar",
          "url": "fa2fomapper-3.0.0-sources.jar",
          "size": 11610,
          "sha512": "a4149066c39b3085554ba7360625fc8230d49c80e70202dd04d30a5f9c44468cb831fb873a6ebd065efb69cc3b0c84d8d5f7394e454a0a00b761142f4b9133a2",
          "sha256": "88552c48416a96183f1dddb90a42e4c19b97b4496afbd5261029af913b7ea278",
          "sha1": "841199e8a45a6f5208446054609bd6fc99c0cdf8",
          "md5": "3699a5750866ea598ae9010787f879cc"
        }
      ]
    }
  ]
}
